on:
  workflow_dispatch:
  pull_request: #can put indented arguments inside of these 
  push:
    branches:
      - main
      
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package and test deps #order does not matter under lists -
        run: pip install -e .[test]

      - run: pytest 
      
